Level properties page
spiretrading/nexus pull request #1093
Opened 2024-11-06 22:34 UTC by shaobinspire

2024-11-06 23:08 UTC, kranar requested changes

2024-11-06 23:08 UTC, kranar commented on Applications/Spire/Source/BookView/BookViewLevelPropertiesPage.cpp
> +    scheme->transact([&] {
Where is ownership of ```scheme``` shared?

2024-11-06 23:08 UTC, kranar commented on Applications/Spire/Source/BookView/BookViewLevelPropertiesPage.cpp
> +  auto make_levels_slot(std::shared_ptr<OptionalIntegerModel> model) {
Don't call a parameter ```model``` anymore than you would call a variable ```variable```.

2024-11-06 23:08 UTC, kranar commented on Applications/Spire/Source/BookView/BookViewLevelPropertiesPage.cpp
> +  PriceLevelWidget( std::shared_ptr<ValueModel<std::vector<QColor>>> source,
Remove whitespace.

2024-11-07 14:56 UTC, shaobinspire commented on Applications/Spire/Include/Spire/Ui/Ui.hpp
> +  int get_default_character_width();
This function returns the character width using the default font of the `TextBox`, which is "Roboto" at 12px with a normal weight.

2024-11-07 15:14 UTC, kranar commented on Applications/Spire/Include/Spire/Ui/Ui.hpp
> +  int get_default_character_width();
Remove it and use only the ```get_character_width``` function.

2024-11-07 16:31 UTC, kranar approved these changes

2024-11-07 16:31 UTC, merged