Ui viewer
spiretrading/nexus pull request #511
Opened 2020-10-09 22:12 UTC by spireken

2020-10-10 00:01 UTC, spireken commented
I debated using something like the Prototype pattern to dynamically instantiate the test widgets, but with the current requirements I kept it simple and straightforward.

2020-10-10 02:22 UTC, kranar requested changes
Huge improvement.

2020-10-10 02:22 UTC, kranar commented on Applications/Spire/Include/Spire/UiViewer/ColorSelectorButtonTestWidget.hpp
> +      ColorSelectorButtonTestWidget(QWidget* parent = nullptr);
Explicit.

2020-10-10 02:22 UTC, kranar commented on Applications/Spire/Include/Spire/UiViewer/UiViewer.hpp
> +  class UiViewerWindow;
Forward declare all classes, helps autocompletion in IDE's.

2020-10-10 02:22 UTC, kranar commented on Applications/Spire/Include/Spire/UiViewer/UiViewerWindow.hpp
> +      UiViewerWindow(QWidget* parent = nullptr);
Explicit.

2020-10-13 16:16 UTC, kranar approved these changes

2020-10-13 16:20 UTC, merged