Button/Box
spiretrading/nexus pull request #588
Opened 2021-02-23 21:46 UTC by shaobinspire

2021-02-23 22:33 UTC, spireken requested changes

2021-02-23 22:33 UTC, spireken commented on Applications/Spire/Include/Spire/Ui/Box.hpp
> +  //! Represents a box container with a spcific styling.
Typo: specific.

2021-02-23 22:33 UTC, spireken commented on Applications/Spire/Include/Spire/Ui/TextBox.hpp
> +      bool m_is_hover;
m_is_hovered

2021-02-23 22:33 UTC, spireken commented on Applications/Spire/Include/Spire/Ui/Box.hpp
> +      bool m_is_hover;
m_is_hovered

2021-02-23 22:35 UTC, spireken commented
An issue I found; the button is supposed to trigger the ClickSignal on a space bar press and release. Currently, it triggers with just a space bar press.

2021-02-23 23:48 UTC, shaobinspire commented
> the button is supposed to trigger the ClickSignal on a space bar press and release.

I implemented it according to the implementation of the FlatButton class. No matter In the current flatbutton specs or the button specs, this is not mentioned. If the button triggers the ClickSignal on a space bar press and release, it means that one click of the space bar will trigger the signal twice. I think it’s abnormal.

2021-02-24 00:30 UTC, spireken commented
It's a subtle detail, but in the flow for the Button specs the flow makes a distinction between an enter 'press' event and a space 'click' event. A 'click' for a key event is a full press/release cycle.

I believe this was based off of certain buttons that made a distinction between the enter/return keys and the space bar, but you would need to ask the designers for the full details.

2021-02-24 19:29 UTC, closed without merging