Button
spiretrading/nexus pull request #590
Opened 2021-03-04 00:38 UTC by shaobinspire

The text color in the hover state doesn't not satisfying the specs of the FlatButton.

2021-03-04 03:16 UTC, kranar requested changes
This is excellent work, looks like several corner cases were taken care of properly.

2021-03-04 03:16 UTC, kranar commented on Applications/Spire/Source/Ui/Button.cpp
> +    case QEvent::MouseButtonPress:
Give the component a chance to handle these events and only if the component doesn't handle them, then the Button can handle it.

2021-03-05 03:32 UTC, kranar reviewed
Overall this is good, let's meet tomorrow on Zoom to go over it a bit more.

2021-03-05 16:41 UTC, shaobinspire reviewed
When the text of the button is overflowed and you click the button, the text is slightly off.

2021-03-05 16:50 UTC, kranar commented
Looks like that happens because the border pushes the text, the text is off just by focusing the button without clicking on it. Can you look into why that happens? Does it happen for TextBox?

2021-03-05 16:55 UTC, kranar commented
It looks like it happens because the border changes from 0x to 1px. To fix it, use a consistent border size but make it transparent.

2021-03-05 17:47 UTC, kranar commented
Shaobin, did you identify any other issue other than the border?

2021-03-05 17:53 UTC, shaobinspire commented
> Shaobin, did you identify any other issue other than the border?

Yes, I found a bug of TextBox. The TextBox can't elide text when it focuses out, because you removed the eventFilter. The FocusInEvent and focusOutEvent is textbox's not qlineedit's.

2021-03-05 17:56 UTC, merged