RowViewListModel
spiretrading/nexus pull request #625
Opened 2021-05-21 19:21 UTC by shaobinspire

2021-05-21 19:59 UTC, spireken approved these changes

2021-05-21 20:46 UTC, kranar requested changes

2021-05-21 20:46 UTC, kranar commented on Applications/Spire/Include/Spire/Ui/RowViewListModel.hpp
> +      boost::optional<int> m_row;
Use a sentinel value of ```-1``` for ```m_row```.

2021-05-21 20:46 UTC, kranar commented on Applications/Spire/Source/Ui/RowViewListModel.cpp
> +    m_row = none;
When ```m_row == -1```, do the following:

    m_source_connection.disconnect();
    m_source = nullptr;

2021-05-21 20:46 UTC, kranar commented on Applications/Spire/Source/Ui/RowViewListModel.cpp
> +  if(!m_row) {
```m_row == -1```

2021-05-21 20:46 UTC, kranar commented on Applications/Spire/Source/Ui/RowViewListModel.cpp
> +        if(m_row && *m_row >= operation.m_index) {
You can remove all of the ```if(m_row ...)``` checks. For ```m_row == -1``` none of the remainder of the condition will hold.

2021-05-22 02:26 UTC, kranar approved these changes
Excellent stuff, well done.

2021-05-22 02:26 UTC, merged