Delete icon button
spiretrading/nexus pull request #638
Opened 2021-06-29 17:14 UTC by spireken

2021-06-29 17:59 UTC, shaobinspire requested changes
There is a border when the button gets focus, but I don't see it in the specs of the DeleteIconButton.

2021-06-29 18:04 UTC, kranar commented on Applications/Spire/Source/Ui/Button.cpp
> +  style.get(Focus() / Body() || Hover() / Body()).
Factor this out ```(Focus() || Hover()) / Body()```

2021-06-29 18:10 UTC, spireken commented
> There is a border when the button gets focus, but I don't see it in the specs of the DeleteIconButton.

The DeleteIconButton is an IconButton so I believe it inherits the IconButton style.

2021-06-29 18:48 UTC, shaobinspire approved these changes

2021-07-06 03:19 UTC, kranar commented
I believe work still needs to be done on this after some changes to icon, resubmit it later.

2021-07-06 03:19 UTC, closed without merging