Search box
spiretrading/nexus pull request #652
Opened 2021-07-15 02:06 UTC by spireken

2021-07-15 14:15 UTC, shaobinspire requested changes

2021-07-15 14:15 UTC, shaobinspire commented on Applications/Spire/Source/Ui/SearchBox.cpp
> +#include <QKeyEvent>
The header file is not used.

2021-07-15 14:53 UTC, shaobinspire approved these changes
Looks great.

2021-07-19 16:07 UTC, kranar commented
Does this need more changes or is it good to go?

2021-07-19 16:08 UTC, spireken commented
> Does this need more changes or is it good to go?

The last update that I got was Jon giving the okay, so as far as I know it just needs your review.

2021-07-19 16:21 UTC, kranar requested changes
Looks good.

2021-07-19 16:21 UTC, kranar commented on Applications/Spire/Include/Spire/Ui/SearchBox.hpp
> +      explicit SearchBox(QWidget* parent = nullptr);
Needs a model.

2021-07-19 16:21 UTC, kranar commented on Applications/Spire/Include/Spire/Ui/SearchBox.hpp
> +    public:
Missing a way to indicate that the user is submitting the search.

2021-07-19 16:21 UTC, kranar commented on Applications/Spire/Source/Ui/SearchBox.cpp
> +      m_delete_button->setVisible(!current.isEmpty());
Move this logic out of the constructor.

2021-07-19 16:21 UTC, kranar commented on Applications/Spire/Source/Ui/SearchBox.cpp
> +    m_text_box->get_model()->set_current({});
Same here.

2021-07-19 17:19 UTC, kranar approved these changes

2021-07-19 17:19 UTC, merged