Scroll box ranges
spiretrading/nexus pull request #674
Opened 2021-08-10 02:12 UTC by spireken

2021-08-10 13:16 UTC, kranar requested changes

2021-08-10 13:16 UTC, kranar commented on Applications/Spire/Source/UiViewer/StandardUiProfiles.cpp
> +          set(PaddingLeft(padding)).
```horizontal_padding```

2021-08-10 13:16 UTC, kranar commented on Applications/Spire/Source/UiViewer/StandardUiProfiles.cpp
> +          set(PaddingTop(padding)).
```vertical_padding```

2021-08-10 14:06 UTC, shaobinspire reviewed
When the padding changes, do the ranges need to be updated?

2021-08-11 00:08 UTC, kranar approved these changes
This is fantastic, I am left speechless. Very straight forward solution to a difficult problem and the demo is excellent.

2021-08-11 00:08 UTC, merged