Side box
spiretrading/nexus pull request #707
Opened 2021-09-15 17:00 UTC by shaobinspire

2021-09-15 17:47 UTC, spireken approved these changes
Looks good.

2021-09-15 18:35 UTC, kranar commented
API was not submitted for review and would not have been approved had it been.

2021-09-16 16:36 UTC, kranar requested changes

2021-09-16 16:36 UTC, kranar commented on Applications/Spire/Source/Ui/SideBox.cpp
> +  return make_side_box(Side::NONE, parent);
```Side::NONE``` is not a valid case, the components.xd specifies that only Buy and Sell are valid.

2021-09-16 16:36 UTC, kranar commented on Applications/Spire/Source/Ui/SideBox.cpp
> +  cases->push(Side(Side::ASK));
Spec orders things buy and sell.

2021-09-16 16:36 UTC, kranar commented on Applications/Spire/Source/Ui/SideBox.cpp
> +  auto settings = SideBox::Settings();
Avoid constantly doing the same work over and over.

2021-09-16 16:36 UTC, kranar commented on Applications/Spire/Source/UiViewer/StandardUiProfiles.cpp
> +    {{"Buy", Side::ASK}, {"Sell", Side::BID}});
Mismatching values.

2021-09-16 20:47 UTC, kranar requested changes

2021-09-16 20:47 UTC, kranar commented on Applications/Spire/Source/Ui/SideBox.cpp
> +    static auto settings = SideBox::Settings();
Use IIFE.

2021-09-16 21:47 UTC, merged