Calendar date picker
spiretrading/nexus pull request #708
Opened 2021-09-15 20:47 UTC by spireken

The tab navigation of the ListView is currently undefined, but everything else should work as expected.

2021-09-15 23:25 UTC, shaobinspire requested changes

2021-09-15 23:25 UTC, shaobinspire commented on Applications/Spire/Source/Ui/CalendarDatePicker.cpp
> +  m_calendar_view->get_selection_model()->set_current(index);
I think it is needed anymore, because the selected can change with current in the updated listview.

2021-09-15 23:25 UTC, shaobinspire commented on Applications/Spire/Source/Ui/CalendarDatePicker.cpp
> +    if(auto current = m_model->get_current();  day == current) {
There is an extra space between ';' and 'day'.

2021-09-15 23:25 UTC, shaobinspire commented on Applications/Spire/Source/Ui/CalendarDatePicker.cpp
> +      [=] (auto index) { on_list_current(index); });
auto -> const auto&

2021-09-15 23:25 UTC, shaobinspire commented on Applications/Spire/Source/Ui/CalendarDatePicker.cpp
> +void CalendarDatePicker::on_list_current(const boost::optional<int> index) {
index should be a reference.

2021-09-16 14:21 UTC, shaobinspire approved these changes

2021-09-20 15:20 UTC, kranar commented on Applications/Spire/Include/Spire/Ui/CalendarDatePicker.hpp
> +  using OptionalDateModel =
Why is this optional? At what point does the date picker produce a ```none```?

2021-09-20 15:56 UTC, closed without merging