The padding styles of the TableBody
spiretrading/nexus pull request #869
Opened 2023-01-25 22:24 UTC by shaobinspire

2023-01-25 22:25 UTC, shaobinspire commented
It is related to [Customize the outer border of the TableBody cell](https://app.asana.com/0/1169210941620249/1203810852741111/f).

2023-01-26 19:23 UTC, kranar requested changes

2023-01-26 19:23 UTC, kranar commented on Applications/Spire/Source/Ui/TableBody.cpp
> +int TableBody::get_left_spacing(int index) {
What mutable operation does this perform?

2023-01-26 19:23 UTC, kranar commented on Applications/Spire/Source/UiViewer/StandardUiProfiles.cpp
> +    property.connect_changed_signal([=] (const int& value) {
Don't pass ```int``` by reference.

2023-01-26 19:23 UTC, kranar commented on Applications/Spire/Source/UiViewer/StandardUiProfiles.cpp
> +  auto connect_style_property_change_signal(TypedUiProperty<int>& property,
What is this trying to do? It looks like it will break properties that are ```int```s.

2023-01-27 20:18 UTC, kranar commented on Applications/Spire/Source/Ui/TableBody.cpp
> +          if(size < 0) {
Prefer expressions over statements:

    m_styles.m_padding.setTop(std::max(0, size));

2023-02-03 20:18 UTC, merged