Order tasks page searching
spiretrading/nexus pull request #882
Opened 2023-02-22 22:32 UTC by shaobinspire

2023-02-22 22:50 UTC, kranar reviewed
Needs to be tested.

2023-03-15 20:16 UTC, shaobinspire commented
@kranar I have added some unit test cases for OrderTaskMatch, MatchCache and TableMatchCache.

2023-03-16 17:29 UTC, kranar requested changes
Looks great.

2023-03-16 17:29 UTC, kranar commented on Applications/Spire/Source/SpireTester/OrderTaskMatchTester.cpp
> +  TEST_CASE("match_order_typ") {
typo

2023-03-16 17:29 UTC, kranar commented on Applications/Spire/Source/SpireTester/TableMatchCacheTester.cpp
> +    auto is_hitted_first_cache = [&] {
Rename ```hitted``` to ```hit```.

2023-03-17 21:53 UTC, merged