TaskKeysTableView
spiretrading/nexus pull request #991
Opened 2024-04-10 19:32 UTC by shaobinspire

I have put a demo to demos/task_key_table_view.
The functions `populate_xxx` in KeyBindingsWindow.cpp are used for testing.

I am currently facing the challenge in adding a PopupBox to the EditableTableView. In the current implementation, the RegionBox is wrapped by the AnyInputBox, which in turn is wrapped by the EditableBox. This EditableBox is then passed to the ViewBuilder of the EditableTableView to construct a cell. However, this structure presents difficulties in integrating a PopupBox seamlessly.

If the PopupBox encapsulates the RegionBox directly, a compatibility issue arises: the AnyInputBox cannot accept the PopupBox since the PopupBox lacks the necessary interfaces such as the Submit signal and read-only related interfaces. Although one potential solution to implement a PopupRegionBox can address this interface compatible issue, it poses another challenge. When EditableBox wraps the PopupRegionBox, the act of popping up the PopupRegionBox will trigger a editing end signal, as the popped component gets focus, so the RegionBox can’t trigger the editing state in the popup status.

Alternatively, if the PopupBox wraps the EditableBox, it could address the issues mentioned above. However this approach will break the signature of the ViewBuilder. The ViewBuilder in EditableTableView returns the pointer to the EditableBox, not a pointer to the QWidget.

2024-04-10 20:01 UTC, kranar requested changes
Still needs a lot of work.

2024-04-10 20:09 UTC, shaobinspire commented on Applications/Spire/Source/KeyBindings/KeyBindingsWindow.cpp
> +  auto populate_order_task_arguments() {
This function is used for testing and will be removed after testing.

2024-04-10 20:10 UTC, shaobinspire commented on Applications/Spire/Source/KeyBindings/KeyBindingsWindow.cpp
> +      {"MSFT.NSDQ", "Microsoft Corporation"},
This function is same as the function `populate_order_task_arguments` and is used for testing.

2024-04-10 20:10 UTC, kranar commented on Applications/Spire/Source/KeyBindings/KeyBindingsWindow.cpp
> +  auto populate_order_task_arguments() {
Never mix tests with implementation.

2024-04-10 20:19 UTC, shaobinspire commented on Applications/Spire/Source/KeyBindings/KeyBindingsWindow.cpp
> +  auto populate_order_task_arguments() {
Where can I populate testing data? In the KeyBindingsModel?

2024-04-10 20:22 UTC, kranar commented on Applications/Spire/Source/KeyBindings/KeyBindingsWindow.cpp
> +  auto populate_order_task_arguments() {
Test code and implementations are separate. Identify which test code is most appropriate to populate your model there. I don't know off the top of my head where that is, I can look later tonight when I get some time.

2024-04-11 01:05 UTC, kranar requested changes

2024-04-11 01:05 UTC, kranar commented on Applications/Spire/Source/KeyBindings/TaskKeysTableView.cpp
> +      [&] (const OrderTaskArgumentsListModel::AddOperation& operation) {
To properly handle transactions you'll need to add the following cases:

    [&] (const StartTransaction&) {
      m_transaction.start();
    },
    [&] (const EndTransaction&) {
      m_transaction.end();
    },

2024-04-11 01:05 UTC, kranar commented on Applications/Spire/Source/KeyBindings/TaskKeysTableView.cpp
> +        for(auto i = 0; i < COLUMN_SIZE; ++i) {
To start a transaction you need to call ```m_transaction.transact(...)```.

2024-04-11 01:05 UTC, kranar commented on Applications/Spire/Source/KeyBindings/TaskKeysTableView.cpp
> +      return key_input_box_validator(key) == QValidator::Acceptable;
It's more robust to test:
    ```test != QValidator::Invalid```

2024-04-11 01:11 UTC, kranar commented
Is it possible to subclass ```PopupBox``` into a ```PopupInputBox``` that adds the methods needed like ```get_current```, ```get_submission```, etc... so that it can plug into an ```AnyInputBox```?

2024-04-11 15:52 UTC, shaobinspire commented
> PopupInputBox

I think it might work. If the EditableBox encapsulates the PopupBox, the popup of the PopupBox will lead to the EditableBox losing focus and reverting to the non-editable state. Unless the PopupInputBox prevents it from being set to read-only on popup. However, if the PopupBox wraps the EditableBox instead, the EditableBox becomes the popup component and it would retain focus for editing state. Hence, I think it's more intuitive for PopupBox to wrap EditableBox.

2024-04-11 15:54 UTC, kranar commented
Perhaps you can subclass the EditableBox into an EditablePopupBox.

2024-04-11 15:56 UTC, shaobinspire commented
> Perhaps you can subclass the EditableBox into an EditablePopupBox.

Good point. I will give it a try.

2024-04-12 17:25 UTC, kranar commented
Was this reviewed by Jon?

2024-04-12 17:26 UTC, shaobinspire commented
> Was this reviewed by Jon?

No. I am going to assign it to Jon for review.

2024-04-15 15:44 UTC, shaobinspire commented
@kranar I have fixed [the task](https://app.asana.com/0/1169210941620249/1207078420458093/f) and updated the code based on code review.

2024-04-15 16:11 UTC, kranar approved these changes
Looks good!

2024-04-15 16:11 UTC, merged